[package]
name = "store_rocksdb"
version = "0.1.0"
edition = "2024"

[dependencies]
rocksdb = { version = "0.22", features = ["multi-threaded-cf"] }
parking_lot = "0.12"
store_traits = { path = "../store_traits" }
anyhow = "1"
tempfile = "3"
rsnano_output_tracker = { path = "../nullables/output_tracker" }
rsnano_types = { path = "../types" }

[dev-dependencies]
rsnano_ledger = { path = "../ledger" }
