[package]
name = "store_traits"
version = "0.1.0"
edition = "2024"

[features]
ledger_snapshots = []

[dependencies]
anyhow = "1"
rsnano_types = { path = "../types" }
rsnano_output_tracker = { path = "../nullables/output_tracker" }
serde = { version = "1", features = ["derive"] }
num-derive = "0"
num-traits = "0"
